version: '3.8'

services:
  # userService:
  #   image: your_user_service_image
  #   build:./path/to/userService
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - mongo
  #     - redis
  #     - rabbitmq

  # subscriptionService:
  #   image: your_subscription_service_image
  #   build:./path/to/subscriptionService
  #   ports:
  #     - "8001:8001"
  #   depends_on:
  #     - mongo
  #     - redis
  #     - rabbitmq

  # newsfeedService:
  #   image: your_newsfeed_service_image
  #   build:./path/to/newsfeedService
  #   ports:
  #     - "8002:8002"
  #   depends_on:
  #     - rabbitmq
  #     - qdrant

  # contentService:
  #   image: your_content_service_image
  #   build:./path/to/contentService
  #   ports:
  #     - "8003:8003"
  #   depends_on:
  #     - rabbitmq
  #     - qdrant

  notificationService:
    container_name: notification
    image: notification-service
    build: ./backend/notification-service
    ports:
      - "8004:8004"
    depends_on:
      - rabbitmq

  # apiGatewayService:
  #   image: your_api_gateway_service_image
  #   build:./path/to/apiGatewayService
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - userService
  #     - subscriptionService
  #     - newsfeedService
  #     - contentService
  #     - notificationService

  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - "80:80"
  #   volumes:
  #     -./nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - apiGatewayService

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "15672:15672"
      - "5672:5672"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      -./qdrant_data:/qdrant/storage
