version: '3.8'

services:
  userService:
    container_name: user
    image: user-service
    build: ./backend/userService
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - redis
      - rabbitmq

  newsfeedService:
    container_name: newsfeed
    image: newsfeed-service
    build: ./backend/newsFeedService
    ports:
      - "8002:8002"
    depends_on:
      - rabbitmq
      - qdrant
      - mongo

  # contentService:
  #   image: your_content_service_image
  #   build:./path/to/contentService
  #   ports:
  #     - "8003:8003"
  #   depends_on:
  #     - rabbitmq
  #     - qdrant

  notificationService:
    container_name: notification
    image: notification-service
    build: ./backend/notificationService
    ports:
      - "8004:8004"
    depends_on:
      - rabbitmq

  subscriptionService:
    container_name: subscription
    image: subscription-service
    build: ./backend/subscriptionService
    ports:
      - "8005:8005"
    depends_on:
      - rabbitmq
      - redis
      - mongo

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      -./nginx.conf:/etc/nginx/nginx.conf

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "15672:15672"
      - "5672:5672"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_data:/qdrant/storage


networks:
