version: "3.8"

services:
  application:
    container_name: application
    image: newsfeed-application
    build: ./frontend/newsfeed
    ports:
      - "3000:3000"
    depends_on:
      - userService
      - subscriptionService
    networks:
      - app_network

  userService:
    container_name: userService
    image: user-service
    build: ./backend/userService
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - redis
      - rabbitmq
    volumes:
      - ./modules:/app/modules
      - ./command:/app/command
    env_file:
      - ./backend/userService/.env
    networks:
      - app_network
    command: 
      [
        "/bin/sh",
        "-c",
        "./command/waitForIt.sh rabbitmq 5672 && node dist/server.js",
      ]

  newsfeedService:
    container_name: newsfeed
    image: newsfeed-service
    build: ./backend/newsFeedService
    ports:
      - "8005:8005"
    depends_on:
      - rabbitmq
      - qdrant
      - mongo
    volumes:
      - ./modules:/app/modules
      - ./command:/app/command
    env_file:
      - ./backend/newsFeedService/.env
    networks:
      - app_network
    command:
      [
        "/bin/bash",
        "-c",
        "./command/waitForIt.sh rabbitmq 5672 && node dist/server.js",
      ]

  contentService:
    container_name: content
    image: content-service
    build: ./backend/contentService
    ports:
      - "8002:8002"
    depends_on:
      - rabbitmq
    volumes:
      - ./modules:/app/modules
      - ./command:/app/command
    env_file:
      - ./backend/contentService/.env
    networks:
      - app_network
    command:
      [
        "/bin/sh",
        "-c",
        "./command/waitForIt.sh rabbitmq 5672 && node dist/server.js",
      ]

  notificationService:
    container_name: notification
    image: notification-service
    build: ./backend/notificationService
    ports:
      - "8003:8003"
    depends_on:
      - rabbitmq
      # - redis # Uncomment this line if you want to use redis for caching notification service
    volumes:
      - ./modules:/app/modules
      - ./command:/app/command
    env_file:
      - ./backend/notificationService/.env
    networks:
      - app_network
    command:
      [
        "/bin/sh",
        "-c",
        "./command/waitForIt.sh rabbitmq 5672 && node dist/server.js",
      ]

  subscriptionService:
    container_name: subscriptionService
    image: subscription-service
    build: ./backend/subscriptionService
    ports:
      - "8004:8004"
    depends_on:
      - rabbitmq
      - redis
      - mongo
    volumes:
      - ./modules:/app/modules
      - ./command:/app/command
    env_file:
      - ./backend/subscriptionService/.env
    networks:
      - app_network
    command:
      [
        "/bin/sh",
        "-c",
        "./command/waitForIt.sh rabbitmq 5672 && node dist/server.js",
      ]

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app_network

  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - app_network

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - app_network

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app_network

  qdrant:
    container_name: qdrant
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_data:/qdrant/storage
    networks:
      - app_network

volumes:
  qdrant_data:
  nginx.conf:
  modules:
  command:

networks:
  app_network:
    driver: bridge
