version: '3.8'

services:

  application:
    container_name: application
    image: newsfeed-application
    build: ./frontend/newsfeed
    ports:
      - "3000:3000"
    depends_on:
      - userService
      - subscriptionService
    networks:
      - applicationNework


  userService:
    container_name: user
    image: user-service
    build: ./backend/userService
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - redis
      - rabbitmq
    networks:
      - applicationNework
    volumes:
      - ./modules:/app/modules
    env_file:
      - ./backend/userService/.env

  newsfeedService:
    container_name: newsfeed
    image: newsfeed-service
    build: ./backend/newsFeedService
    ports:
      - "8005:8005"
    depends_on:
      - rabbitmq
      - qdrant
      - mongo
    volumes:
      - ./modules:/app/modules
    env_file:
      - ./backend/newsFeedService/.env
    

  contentService:
    container_name: content
    image: content-service
    build: ./backend/contentService
    ports:
      - "8002:8002"
    depends_on:
      - rabbitmq
    volumes:
      - ./modules:/app/modules
    env_file:
      - ./backend/contentService/.env

  notificationService:
    container_name: notification
    image: notification-service
    build: ./backend/notificationService
    ports:
      - "8003:8003"
    depends_on:
      - rabbitmq
      # - redis # Uncomment this line if you want to use redis for caching notification service
    volumes:
      - ./modules:/app/modules
    env_file:
      - ./backend/notificationService/.env

  subscriptionService:
    container_name: subscription
    image: subscription-service
    build: ./backend/subscriptionService
    ports:
      - "8004:8004"
    depends_on:
      - rabbitmq
      - redis
      - mongo
    networks:
      - applicationNework
    volumes:
      - ./modules:/app/modules
    env_file:
      - ./backend/subscriptionService/.env

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    networks:
      - applicationNework
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "15672:15672"
      - "5672:5672"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
      - "8010:8010"

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_data:/qdrant/storage

volumes:
  qdrant_data:
  nginx.conf:
  modules:
     

networks:
  applicationNework:
    driver: bridge
  
